Algoritmo "Conversão de Real para Dolar"

Var
 Dolar, Reais, Resultado : real


Inicio
      escreva("Digite a quantidade de Reais que quer converter para dolar")
             leia(Reais)
      escreva("digite a atual cotação do dolar")
             leia(Dolar)
             
      Resultado<- Reais/Dolar
      
      escreval(" A quantidade de dolares que você vai adquirir é igual a:", Resultado)



Fimalgoritmo